FORMAT: 1A
HOST: http://localhost:3333

# Bookcase

Bookcase is an application for managing books.

## Authentication

Bookcase API uses Bearer Token Authentication. First you create a new user and request your token.

`Authorization: bearer 5262d64b892e8d4341000001`

## Error States

The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

## Group Books

Resources related to books.

## Books Collection [/books/{id}]

### Index [GET]

List all books from auth user.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "user_id": 1,
                "title": "O Hobbit",
                "author": "J. R. R. Tolkien",
                "number_pages": 310,
                "description": "Bilbo Bolseiro é um hobbit que leva uma vida confortável e sem ambições, raramente aventurando-se para além de sua despensa ou sua adega. Mas seu contentamento é perturbado quando Gandalf, o mago, e uma companhia de anões batem em sua porta e levam-no para uma expedição.",
                "cover": "http://127.0.0.1:3333/covers/1567258600971.png",
                "created_at": "2019-05-17 20:37:11",
                "updated_at": "2019-08-31 10:39:44",
                "tags": []
            },
            {
                "id": 2,
                "user_id": 1,
                "title": "O Silmarillion",
                "author": "J. R. R. Tolkien",
                "number_pages": 365,
                "description": "O Silmarillion, publicado quatro anos após o falecimento do seu autor, é um relato dos Dias Antigos, a Primeira Era do Mundo. Em O Senhor dos Anéis, foram narrados os grandes eventos do final da Terceira Era; as histórias de O Silmarillion, no entanto, são lendas derivadas de um passado muito mais remoto, quando Morgoth, o primeiro Senhor do Escuro, habtava a Terra-média, e os altos-elfos guerrearam com ele pela recuperação das Silmarils.\nMas O Silmarillion não relata apenas os eventos de uma época muito anterior àquela de O Senhor dos Anéis em todos os pontos essenciais de sua concepção, ele também é, de longe, a obra mais antiga. Na realidade, embora na época não chamasse O Silmarillion, já existia meio século antes. Em cadernos velhíssimos, que remontam a 1917, podem ser lidas as versões iniciais das histórias mais importantes da mitologia, muitas vezes escritas às pressas, à lápis.",
                "cover": "http://127.0.0.1:3333/covers/1567255576379.jpeg",
                "created_at": "2019-05-17 20:37:51",
                "updated_at": "2019-08-31 10:41:41",
                "tags": []
            }
        ]

### Create [POST]

You may register your book.
Request containing the attributes below:

+ title (string, required) - The title
+ author (string) - The author
+ number_pages (string) - The number of pages
+ description (string) - The description
+ review (string) - The complete review about the book
+ cover (file) - The file that represents the book cover
+ rating (integer) - The rating about the book
+ status (enum) - The status ['READING', 'WANT_READ', 'READ', 'REREADING', 'ABANDONED']
+ tags (array) - ID's of the tags

+ Request

    + Headers

            Content-Type: multipart/form-data

+ Response 201 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "title": "O Hobbit",
            "author": "J. R. R. Tolkien",
            "number_pages": 310,
            "description": "Bilbo Bolseiro é um hobbit que leva uma vida confortável e sem ambições, raramente aventurando-se para além de sua despensa ou sua adega. Mas seu contentamento é perturbado quando Gandalf, o mago, e uma companhia de anões batem em sua porta e levam-no para uma expedição.",
            "cover": "http://127.0.0.1:3333/covers/1567258600971.png",
            "created_at": "2019-05-17 20:37:11",
            "updated_at": "2019-05-17 20:37:11"
        }

### Show [GET]

Show an especific Book.

+ Parameters

    + id: 1 (required, number) - The book ID

+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "title": "O Hobbit - Atualizado",
            "author": "J. R. R. Tolkien",
            "number_pages": 310,
            "description": "Bilbo Bolseiro é um hobbit que leva uma vida confortável e sem ambições, raramente aventurando-se para além de sua despensa ou sua adega. Mas seu contentamento é perturbado quando Gandalf, o mago, e uma companhia de anões batem em sua porta e levam-no para uma expedição.",
            "cover": "http://127.0.0.1:3333/covers/1567258600971.png",
            "created_at": "2019-05-17 20:37:11",
            "updated_at": "2019-08-31 10:39:44",
            "tags": []
        }

+ Response 401 (application/json)

        {
            error: "Not authorized."
        }

### Update [PUT]

Update an existing book.
Request may containing the attributes below:

+ title (string) - The title
+ author (string) - The author
+ number_pages (string) - The number of pages
+ description (string) - The description
+ review (string) - The complete review about the book
+ cover (file) - The file that represents the book cover
+ rating (integer) - The rating about the book
+ status (enum) - The status ['READING', 'WANT_READ', 'READ', 'REREADING', 'ABANDONED']
+ tags (array) - ID's of the tags

+ Parameters

    + id: 1 (required, number) - The book ID

+ Request

    + Headers

            Content-Type: multipart/form-data

+ Response 200 (application/json)

        {
            "id": 1,
            "user_id": 1,
            "title": "O Hobbit - Atualizado",
            "author": "J. R. R. Tolkien",
            "number_pages": 310,
            "description": "Bilbo Bolseiro é um hobbit que leva uma vida confortável e sem ambições, raramente aventurando-se para além de sua despensa ou sua adega. Mas seu contentamento é perturbado quando Gandalf, o mago, e uma companhia de anões batem em sua porta e levam-no para uma expedição.",
            "cover": "http://127.0.0.1:3333/covers/1567258600971.png",
            "created_at": "2019-05-17 20:37:11",
            "updated_at": "2019-08-31 10:39:44",
            "tags": []
        }

+ Response 401 (application/json)

        {
            error: "Not authorized."
        }

### Delete [DELETE]

Delete an existing book.

+ Parameters
    + id: 1 (required, number) - The book ID

+ Response 200 (application/json)

        {
            message: "Book deleted."
        }

+ Response 401 (application/json)

        {
            error: "Not authorized."
        }
